# Generated by Django 4.1.3 on 2023-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=250)),
                ('resolution', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('IMDB_point', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('actor', models.ManyToManyField(related_name='actor_rel_home', to='home.actor')),
                ('director', models.ManyToManyField(related_name='director_rel_home', to='home.director')),
                ('genre', models.ManyToManyField(related_name='genre_rel_home', to='home.genre')),
            ],
        ),
    ]
