# Generated by Django 4.2.1 on 2023-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_country_resolution_remove_movie_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, null=True, related_name='actor_rel_home', to='home.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='country_rel_home', to='home.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='director_rel_home', to='home.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_rel_home', to='home.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='resolution',
            field=models.ManyToManyField(blank=True, null=True, related_name='resolution_rel_home', to='home.resolution'),
        ),
    ]
