# Generated by Django 4.2.1 on 2023-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_movie_actor_alter_movie_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publication',
            field=models.IntegerField(default=0),
        ),
    ]
