# Generated by Django 4.1.3 on 2023-08-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_typedownload_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='download_url',
            field=models.URLField(default='https://www.example.com/download', help_text='<h2>Enter a URL to download file</h2>'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
