# Generated by Django 4.2.1 on 2023-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_movie_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=0)),
                ('Volume', models.IntegerField(default=0)),
                ('title', models.ManyToManyField(blank=True, null=True, related_name='title_rel_home', to='home.movie')),
                ('type', models.ManyToManyField(blank=True, null=True, related_name='type_rel_home', to='home.typedownload')),
            ],
        ),
    ]
