# Generated by Django 4.1.3 on 2023-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_download_download_url_alter_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_url',
            field=models.URLField(default='/search?q='),
        ),
    ]
