# Generated by Django 4.1.3 on 2023-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_genre_genre_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_url',
            field=models.CharField(default='/search?q=', max_length=500),
        ),
    ]
