# Generated by Django 4.2.1 on 2023-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_tag_remove_movie_genre_delete_genre_movie_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='Volume',
            field=models.CharField(max_length=50),
        ),
    ]
