# Generated by Django 4.2.1 on 2023-08-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_download_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='resolution',
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
